# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b1c23dbb79356d3a4bb291aba5439803"
name = "epir-ai-platform-v2"
application_url = "https://epir-gateway-worker.krzysztofdzugaj.workers.dev"
embedded = true

[build]
dev_store_url = "epir-jewelry-development.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_customers,write_orders"

[auth]
redirect_urls = [
  "https://example.com/api/auth/callback",
  "https://localhost:3000/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [webhooks.private_metafield_versions]
  enabled = true

  
[[webhooks.subscriptions]]
uri = "https://example.com/api/webhooks"
topics = ["app/uninstalled"]

[app_proxy]
url = "https://epir-gateway-worker.krzysztofdzugaj.workers.dev" # Your Cloudflare Gateway URL
subpath = "chat"
prefix = "apps"

[pos]
embedded = false
